version: '3'
services:
  ebp-frontend:
    container_name: ebp-frontend
    image: nginx:alpine
    ports:
      - 3001:80
#    build: .

    volumes:
      - ./nginx/proxy.prod.conf:/etc/nginx/conf.d/default.conf
      - ./dist:/www/dist
      - ./docs:/www/dist/docs
      - ./reports:/www/dist/reports
      - ./media:/www/dist/media
